### ISSUE TITLE
Empty ipv4_cidr_blocks.lst files

### ISSUE THREAD

**Issue by fewdji** [SecOps-Institute/TwitterIPLists#1]
Hi!
I was parsing ipv4 from **twitter_ipv4_cidr_blocks.lst** and **facebook_ipv4_cidr_blocks.lst** to use for unlocking.
Now theese files are empty.. Could you fix it, please?

**Comment by aarvee11** [comment]
Apologies as we ran out of funds. We target to resume by 29th Feb 2024. 

We sincerely thank you for the support, trust and patience.

**Comment by aarvee11** [comment]
Please check now. Still the lists are not getting updated hourly as done previously. Working on the same

**Comment by fewdji** [comment]
Nice! Thank you!
